version: '3.9'

services:
    mongo:
        container_name: mongo
        image: mongo
        hostname: mongo
        ports:
            - 27017:27017
        networks:
            - default
        command: [--auth]
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=rootPassXXX
            - MONGO_INITDB_DATABASE=Connections
        volumes:
            - ./mongo-volume:/data/db
        #     - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    api:
        container_name: api
        build: ./api
        ports:
            - 3000:3000
        networks:
            - default
        environment: 
            - USERNAME=root
            - PASSWORD=rootPassXXX
            - DB=mongo
            - PORT=27017
            - DATABASE=Connections
            - PARAMS=?authSource=admin
            - SECRET=MyLittleSecret
    frontend: 
        container_name: frontend
        build: ./frontend
        environment:
            - PORT=4200
        ports:
            - 4200:4200
        depends_on: 
            - api
        networks:
            - default
networks: 
    default:
